"""Rewind a training run to an earlier iteration.

A run can wander into a worse region (a bad hyperparameter experiment, a broken
target) and never recover, because every later round trains on data generated by
the degraded net. The fix is to go back to the last version that was actually
strong and continue from there.

This rewrites the checkpoint directory so that `--resume` genuinely restarts from
iteration N:
  * best.pt          <- versions/vN.pt
  * versions/        <- snapshots after N deleted
  * metrics.jsonl    <- rows after N dropped
  * ratings.json     <- matches involving deleted versions dropped, Elo refit
  * ab_bench.jsonl   <- rows for champions after N dropped
The whole directory is copied to a backup first; nothing is destroyed in place.

Run:  python3 -m alphazero.rollback --to 24
      python3 -m alphazero.rollback --to 24 --dry-run
"""
import os
import json
import shutil
import argparse

import torch

from .config import Config
from .rating import ResultBook, compute_elo


def _vnum(vid):
    """Numeric iteration of a 'v<N>' id; -1 for non-version participants
    ('random', 'alphabeta', 'ref:...') so they are never treated as rollable."""
    tail = vid.rsplit(":", 1)[-1]
    if vid.startswith("ref:") or not tail.startswith("v"):
        return -1
    return int(tail[1:]) if tail[1:].isdigit() else -1


def rollback(cfg, to_iter, dry_run=False, backup_dir=None):
    ck = cfg.ckpt_dir
    vdir = os.path.join(ck, "versions")
    target = os.path.join(vdir, f"v{to_iter}.pt")
    if not os.path.exists(target):
        raise SystemExit(f"[rollback] no snapshot for iteration {to_iter} at {target}")

    backup = backup_dir or f"{ck.rstrip('/')}.before-rollback-v{to_iter}"
    plan = []

    # ---- versions to delete
    doomed = sorted((fn for fn in os.listdir(vdir)
                     if fn.endswith(".pt") and _vnum(os.path.splitext(fn)[0]) > to_iter),
                    key=lambda fn: _vnum(os.path.splitext(fn)[0]))
    plan.append(f"delete {len(doomed)} version snapshot(s): "
                f"{', '.join(os.path.splitext(f)[0] for f in doomed) or '(none)'}")

    # ---- metrics rows to drop
    rows = []
    if os.path.exists(cfg.metrics_file):
        with open(cfg.metrics_file) as f:
            rows = [json.loads(l) for l in f if l.strip()]
    kept_rows = [r for r in rows if r["iter"] <= to_iter]
    plan.append(f"metrics.jsonl: keep {len(kept_rows)} of {len(rows)} rows")

    # ---- ratings: drop every match involving a deleted version, refit Elo
    rpath = os.path.join(ck, "ratings.json")
    rd = {}
    if os.path.exists(rpath):
        with open(rpath) as f:
            rd = json.load(f)
    results = rd.get("results", [])
    kept_results = [e for e in results
                    if _vnum(e["a"]) <= to_iter and _vnum(e["b"]) <= to_iter]
    plan.append(f"ratings.json: keep {len(kept_results)} of {len(results)} match records")

    book = ResultBook.from_list(kept_results)
    elo = compute_elo(book, anchor=cfg.elo_anchor, anchor_elo=cfg.elo_anchor_value,
                      prior_draws=cfg.elo_prior_draws) if book.d else {}
    games = book.games_played()
    kept_versions = [v for v in rd.get("versions", [])
                     if v.get("ref") or _vnum(v["id"]) <= to_iter]
    for v in kept_versions:
        v["elo"] = round(elo.get(v["id"], 0.0), 1)
        v["games"] = int(games.get(v["id"], 0))
        v["best"] = (v["id"] == f"v{to_iter}")
    plan.append(f"ratings.json: v{to_iter} refit Elo = {elo.get(f'v{to_iter}', 0.0):.1f} "
                f"(was {rd.get('elo', {}).get(f'v{to_iter}', float('nan')):.1f})")

    # ---- ab_bench rows for champions after N
    abp = cfg.ab_bench_file
    ab_rows = []
    if os.path.exists(abp):
        with open(abp) as f:
            ab_rows = [json.loads(l) for l in f if l.strip()]
    kept_ab = [r for r in ab_rows if r.get("champion_iter", 0) <= to_iter]
    plan.append(f"ab_bench.jsonl: keep {len(kept_ab)} of {len(ab_rows)} rows")

    plan.append(f"best.pt <- versions/v{to_iter}.pt")
    plan.append(f"backup of {ck}/ -> {backup}/")

    print(f"[rollback] plan (rewind {ck} to iteration {to_iter}):")
    for line in plan:
        print(f"  - {line}")
    if dry_run:
        print("[rollback] --dry-run: nothing written")
        return

    # ---- execute. Backup first: everything below is destructive.
    if os.path.exists(backup):
        raise SystemExit(f"[rollback] backup {backup} already exists — move it away first")
    shutil.copytree(ck, backup)

    for fn in doomed:
        os.remove(os.path.join(vdir, fn))

    with open(cfg.metrics_file, "w") as f:
        for r in kept_rows:
            f.write(json.dumps(r) + "\n")

    with open(rpath, "w") as f:
        json.dump({**rd,
                   "best_iter": to_iter,
                   "elo": {k: round(v, 1) for k, v in elo.items()},
                   "versions": kept_versions,
                   "results": book.to_list()}, f)

    if ab_rows:
        with open(abp, "w") as f:
            for r in kept_ab:
                f.write(json.dumps(r) + "\n")

    # best.pt keeps the training loop's format: arch + state + cfg + extra
    d = torch.load(target, map_location="cpu", weights_only=False)
    torch.save({"arch": d["arch"], "state": d["state"], "cfg": cfg.to_dict(),
                "extra": {"iter": to_iter, "version": to_iter,
                          "elo": round(elo.get(f"v{to_iter}", 0.0), 1)}},
               os.path.join(ck, "best.pt"))

    with open(os.path.join(ck, "status.json"), "w") as f:
        json.dump({"iter": to_iter, "phase": "rolled-back", "games": 0, "buffer": 0}, f)

    print(f"[rollback] done. Backup at {backup}/")
    print(f"[rollback] `--resume` will now continue from iteration {to_iter + 1}.")
    print("[rollback] the replay buffer is not persisted — resume with "
          "--prefill 1.0 so the first trained round sees a full buffer.")


def main():
    d = Config()
    ap = argparse.ArgumentParser(description="Rewind an AlphaZero run to an earlier iteration")
    ap.add_argument("--to", type=int, required=True, help="iteration to rewind to (a saved vN)")
    ap.add_argument("--ckpt-dir", default=d.ckpt_dir, dest="ckpt_dir")
    ap.add_argument("--backup-dir", default=None, dest="backup_dir")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()
    cfg = Config(ckpt_dir=a.ckpt_dir,
                 metrics_file=os.path.join(a.ckpt_dir, "metrics.jsonl"),
                 ab_bench_file=os.path.join(a.ckpt_dir, "ab_bench.jsonl"))
    rollback(cfg, a.to, dry_run=a.dry_run, backup_dir=a.backup_dir)


if __name__ == "__main__":
    main()
